version: '2.4'
services:
  varnish:
    image: kyos0109/varnish60-distroless:6.0-1
    hostname: varnish-server
    volumes:
      - ./conf/varnish.vcl:/default.vcl:ro
      - /tmp
    command: ["-f", "/default.vcl"]
    ports:
      - 8080:80
    networks:
      - happy
    depends_on:
      - nginx

  varnishncsa:
    image: kyos0109/varnish60-distroless:6.0-1
    pid: service:varnish
    network_mode: service:varnish
    entrypoint: varnishncsa
    command: ["-n", "/tmp", "-b", "-a", "-w", "/var/log/varnish"]
    volumes:
      - ./log/syslog:/var/log
    volumes_from:
      - varnish:ro
    depends_on:
      - varnish

  rsyslog-varnish:
    image: kyos0109/rsyslog-docker-slim:8.24.0-1
    pid: service:varnish
    network_mode: service:varnish
    volumes:
      - ./log/syslog:/var/log
      - ./conf/rsyslog.conf:/etc/rsyslog.conf:ro
    depends_on:
      - varnish

  nginx:
    image: kyos0109/nginx-distroless:1.14.0-3
    networks:
      - happy
    tmpfs: /var/cache/nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./wordpress:/usr/share/nginx/html
    depends_on:
      - php-wp

  rsyslog-nginx:
    image: kyos0109/rsyslog-docker-slim:8.24.0-1
    pid: service:nginx
    network_mode: service:nginx
    volumes:
      - ./log/syslog:/var/log
      - ./conf/rsyslog.conf:/etc/rsyslog.conf:ro
    volumes_from:
      - varnish:ro
    depends_on:
      - nginx

  php-wp:
    build:
      context: ./build
      dockerfile: 7.2.10-fpm-wordpress
    volumes:
      - ./wordpress:/usr/share/nginx/html
    networks:
      - happy
      - backend
    depends_on:
      - db

  db:
    image: mariadb:10.3-bionic
    networks:
      - backend
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DBRootPass}
      MYSQL_DATABASE: ${DBName}
      MYSQL_USER: ${DBUser}
      MYSQL_PASSWORD: ${DBPass}

networks:
  happy: {}
  backend: {}